# Generated by Django 5.2.1 on 2025-05-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='viewCount',
            new_name='view_count',
        ),
    ]
