# Generated by Django 5.2.1 on 2025-09-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_google_file_id_post_image_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_uuid',
            field=models.UUIDField(default=None, editable=False, unique=True),
        ),
    ]
