# Generated by Django 5.2.1 on 2025-09-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_post_featured_image_alter_post_image_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.TextField(default='no image'),
        ),
    ]
