# Generated by Django 5.2.1 on 2025-09-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='google_file_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
