# Generated by Django 5.2.1 on 2025-09-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_post_google_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
