# Generated by Django 5.2.1 on 2025-07-23 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0012_alter_workopportunity_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_level', models.CharField(choices=[('bachelors', 'Bachelors'), ('masters', 'Masters'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('phd', 'PhD'), ('associate', 'Associate'), ('postgraduate_diploma', 'Postgraduate Diploma')], default='bachelors', help_text='The academic level of the program.', max_length=50)),
                ('duration_in_years', models.PositiveIntegerField(help_text='Duration of the course in years.')),
                ('cost_of_living', models.PositiveIntegerField(help_text='Estimated annual cost of living in USD.')),
                ('next_intake', models.DateField(help_text='The next intake date for the course.')),
                ('about', models.TextField(help_text='Detailed information about the course.', max_length=10000)),
                ('start_date', models.DateField(help_text='The official start date of the course.')),
                ('submission_deadline', models.DateField(help_text='Final date for submitting the application.')),
                ('offshore_onshore_deadline', models.DateField(help_text='Deadline for offshore/onshore applications.')),
                ('brochure_url', models.URLField(help_text='Link to the course brochure.')),
                ('university', models.ForeignKey(help_text='The university offering this course.', on_delete=django.db.models.deletion.PROTECT, to='university.university')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['university', 'program_level', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='CostOfLivingBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Housing, Transport, Food).', max_length=1000)),
                ('cost', models.PositiveIntegerField(help_text='Cost in USD.')),
                ('course', models.ForeignKey(help_text='The course to which this cost is associated.', on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakdown', to='course.course')),
            ],
            options={
                'verbose_name': 'Cost of Living Item',
                'verbose_name_plural': 'Cost of Living Breakdown',
            },
        ),
    ]
