# Generated by Django 5.2.1 on 2025-08-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program_name',
            field=models.CharField(default='', max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
