# Generated by Django 5.2.1 on 2025-08-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_program_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cost_of_living',
        ),
    ]
