# Generated by Django 5.2.1 on 2025-08-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_cost_of_living'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program_name',
            field=models.CharField(max_length=1000),
        ),
    ]
