# Generated by Django 5.2.1 on 2025-08-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tution_fees',
            field=models.PositiveIntegerField(default=0, help_text='Cost of the course in USD'),
            preserve_default=False,
        ),
    ]
