# Generated by Django 5.2.1 on 2025-11-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_course_tution_fees"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CostOfLivingBreakdown",
        ),
    ]
