# Generated by Django 5.2.1 on 2026-02-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_delete_costoflivingbreakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program_level',
            field=models.CharField(choices=[('foundation', 'Foundation / Pathway'), ('associate', 'Associate'), ('bachelors', 'Bachelors'), ('honours', 'Honours'), ('graduate_certificate', 'Graduate Certificate'), ('graduate_diploma', 'Graduate Diploma'), ('postgraduate_diploma', 'Postgraduate Diploma'), ('masters', 'Masters'), ('professional_doctorate', 'Professional Doctorate'), ('phd', 'PhD'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], default='bachelors', help_text='The academic level of the program.', max_length=50),
        ),
    ]
