# Generated by Django 5.2.1 on 2025-07-22 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0011_alter_costofliving_food_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type of expense (e.g. tuition, travel, accommodation)', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Expense Type',
                'verbose_name_plural': 'Expense Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the scholarship', max_length=1000, unique=True)),
                ('awarded_by', models.CharField(help_text='Organization or institution awarding the scholarship', max_length=1000)),
                ('overview', models.TextField(help_text='Short overview of the scholarship')),
                ('details', models.TextField(help_text='Detailed description of the scholarship')),
                ('amount_details', models.TextField(help_text='Information about amount distribution or breakdown')),
                ('course', models.CharField(help_text='Course or program eligible for the scholarship', max_length=100)),
                ('deadline', models.DateField(help_text='Application deadline for the scholarship')),
                ('intake_year', models.DateField(help_text='Year of intake the scholarship applies to')),
                ('amount', models.PositiveIntegerField(help_text='Total amount awarded (in local currency)')),
                ('no_of_students', models.CharField(help_text='Number of students who will receive this scholarship', max_length=100)),
                ('type_of_scholarship', models.CharField(help_text='Type/category of the scholarship', max_length=255)),
                ('brochure', models.URLField(blank=True, help_text='Link to a PDF brochure or webpage', max_length=1000, null=True)),
                ('country', models.ForeignKey(help_text='Country where the scholarship applies', on_delete=django.db.models.deletion.PROTECT, to='university.country')),
                ('eligible_nationalities', models.ManyToManyField(help_text='Countries whose citizens are eligible for this scholarship', related_name='eligible_scholarships', to='university.country')),
                ('university', models.ManyToManyField(help_text='Universities offering or associated with this scholarship', related_name='scholarships', to='university.university')),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(db_index=True, help_text='Frequently asked question')),
                ('answer', models.TextField(help_text='Answer to the question')),
                ('scholarship', models.ForeignKey(help_text='Scholarship this FAQ belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='scholarship.scholarship')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['scholarship', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipExpenseCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_covered', models.BooleanField(default=False, help_text='Check if this expense is covered by the scholarship')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarship.expensetype')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_coverages', to='scholarship.scholarship')),
            ],
            options={
                'verbose_name': 'Scholarship Expense Coverage',
                'verbose_name_plural': 'Scholarship Expense Coverages',
                'ordering': ['scholarship', 'expense_type'],
                'unique_together': {('scholarship', 'expense_type')},
            },
        ),
    ]
