# Generated by Django 5.2.1 on 2025-08-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstaEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_text', models.TextField(help_text='Paste the Instagram embed HTML blockquote here (without the <script> tag).', verbose_name='Embed HTML')),
                ('is_active', models.BooleanField(default=True, help_text='Only active embeds will be exposed via the API.')),
            ],
            options={
                'verbose_name': 'Instagram Embed',
                'verbose_name_plural': 'Instagram Embeds',
            },
        ),
    ]
