# Generated by Django 5.2.1 on 2025-08-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instaembed',
            name='embed_text',
            field=models.TextField(help_text='Paste the Instagram embed HTML blockquote here (without the <code>&lt;script&gt;</code> tag).', verbose_name='Embed HTML'),
        ),
    ]
