# Generated by Django 5.2.1 on 2025-05-27 07:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='authToken',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
