# Generated by Django 5.2.1 on 2025-05-29 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_employee_authtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
