# Generated by Django 5.2.1 on 2025-06-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='job_roles',
        ),
        migrations.AddField(
            model_name='jobrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='job_roles', to='authentication.permission', verbose_name='Permissions'),
        ),
    ]
