# Generated by Django 5.2.1 on 2025-06-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_permission_job_roles_jobrole_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='api_key',
        ),
    ]
