# Generated by Django 5.2.1 on 2025-06-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_delete_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_roles',
            field=models.ManyToManyField(blank=True, null=True, to='authentication.jobrole', verbose_name='Job Roles'),
        ),
    ]
