# Generated by Django 5.2.1 on 2025-06-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_employee_job_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_roles',
            field=models.ManyToManyField(blank=True, to='authentication.jobrole', verbose_name='Job Roles'),
        ),
    ]
