# Generated by Django 5.2.1 on 2025-07-26 16:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0012_alter_workopportunity_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number (9-15 digits, optional +).', regex='^\\+?1?\\d{9,15}$')])),
                ('auth_token', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShortlistedUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by_students', to='university.university')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_universities', to='student.student')),
            ],
            options={
                'verbose_name': 'Shortlisted University',
                'verbose_name_plural': 'Shortlisted Universities',
                'unique_together': {('student', 'university')},
            },
        ),
    ]
