# Generated by Django 5.2.1 on 2025-07-26 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_shortlisteduniversity_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('GRE', 'GRE'), ('GMAT', 'GMAT'), ('TOEFL', 'TOEFL'), ('IELTS', 'IELTS')], help_text='Main aptitude exam', max_length=50)),
                ('english_exam_type', models.CharField(choices=[('TOEFL', 'TOEFL'), ('IELTS', 'IELTS'), ('PTE', 'PTE'), ('Duolingo', 'Duolingo')], help_text='English proficiency exam', max_length=50)),
                ('date', models.DateField()),
                ('listening_score', models.PositiveIntegerField()),
                ('reading_score', models.PositiveIntegerField()),
                ('writing_score', models.PositiveIntegerField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_scores', to='student.student')),
            ],
            options={
                'verbose_name': 'Test Score',
                'verbose_name_plural': 'Test Scores',
            },
        ),
    ]
