# Generated by Django 5.2.1 on 2025-07-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_document_doc_type_alter_document_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='auth_token',
            new_name='authToken',
        ),
    ]
