# Generated by Django 5.2.1 on 2025-07-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_auth_token_student_authtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
