# Generated by Django 5.2.1 on 2025-07-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
