# Generated by Django 5.2.1 on 2025-07-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_testscores_listening_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
