# Generated by Django 5.2.1 on 2025-08-18 12:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_tution_fees'),
        ('student', '0010_student_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by_students', to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_courses', to='student.student')),
            ],
            options={
                'verbose_name': 'Shortlisted Course',
                'verbose_name_plural': 'Shortlisted Courses',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
