# Generated by Django 5.2.1 on 2025-08-31 16:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_shortlistedcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs', models.TextField()),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentLogs', to='student.student')),
            ],
            options={
                'verbose_name': 'Student Log',
                'verbose_name_plural': 'Student Logs',
                'db_table': 'student_logs',
                'ordering': ['-added_on'],
            },
        ),
    ]
