# Generated by Django 5.2.1 on 2025-09-25 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_bucket_student_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Enter the phone number associated with the OTP.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('otp', models.CharField(help_text='6-digit OTP code.', max_length=6, validators=[django.core.validators.RegexValidator(message='OTP must be exactly 6 digits.', regex='^\\d{6}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='idx_otp_phone')],
            },
        ),
    ]
