# Generated by Django 5.2.1 on 2025-09-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_otprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPRequest',
        ),
    ]
