# Generated by Django 5.2.1 on 2025-09-29 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('student', '0015_delete_otprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='authentication.employee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='student.student')),
            ],
            options={
                'verbose_name': 'Call Request',
                'verbose_name_plural': 'Call Requests',
                'indexes': [models.Index(fields=['student'], name='student_cal_student_f7f16f_idx'), models.Index(fields=['employee'], name='student_cal_employe_883617_idx'), models.Index(fields=['requested_on'], name='student_cal_request_73d6fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'employee'), name='unique_student_employee_request')],
            },
        ),
    ]
