# Generated by Django 5.2.1 on 2025-09-29 18:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('student', '0016_callrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedCounsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_students', to='authentication.employee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_counsellors', to='student.student')),
            ],
            options={
                'verbose_name': 'Assigned Counsellor',
                'verbose_name_plural': 'Assigned Counsellors',
                'ordering': ['-assigned_on'],
                'unique_together': {('student', 'employee')},
            },
        ),
    ]
