# Generated by Django 5.2.1 on 2025-10-02 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_assignedcounsellor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(help_text='Enter a 10-digit phone number.', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Enter the phone number associated with the OTP.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('otp', models.CharField(help_text='6-digit OTP code.', max_length=6, validators=[django.core.validators.RegexValidator(message='OTP must be exactly 6 digits.', regex='^\\d{6}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='idx_otp_phone')],
            },
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
