# Generated by Django 5.2.1 on 2025-10-02 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_student_phone_number_alter_student_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternatePhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_phone', to='student.student')),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
                'ordering': ['phone_number'],
            },
        ),
    ]
