# Generated by Django 5.2.1 on 2025-10-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_alternatephonenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlternatePhoneNumber',
        ),
    ]
