# Generated by Django 5.2.1 on 2025-10-02 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_delete_alternatephonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=9999999999, help_text='Enter a 10-digit phone number.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
    ]
