# Generated by Django 5.2.1 on 2025-10-02 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_alter_student_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('Passport', 'Passport'), ('Transcript', 'Transcript'), ('Degree Certificate', 'Degree Certificate'), ('Recommendation Letter', 'Recommendation Letter'), ('Statement of Purpose', 'Statement of Purpose'), ('Resume', 'Resume'), ('Test Score Report', 'Test Score Report'), ('ID Proof', 'ID Proof'), ('Other', 'Other')], max_length=100)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('processing', 'Processing')], default='uploaded', max_length=50)),
                ('file_id', models.CharField(max_length=255)),
                ('file_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='student.student')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['name'],
            },
        ),
    ]
