# Generated by Django 5.2.1 on 2025-10-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='student',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
