# Generated by Django 5.2.1 on 2025-11-09 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_course_tution_fees"),
        ("student", "0023_remove_student_password_student_is_otp_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="sub_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("Passport", "Passport"),
                    ("Transcript", "Transcript"),
                    ("Degree Certificate", "Degree Certificate"),
                    ("Recommendation Letter", "Recommendation Letter"),
                    ("Statement of Purpose", "Statement of Purpose"),
                    ("Resume", "Resume"),
                    ("Test Score Report", "Test Score Report"),
                    ("ID Proof", "ID Proof"),
                    ("Marksheet", "Marksheet"),
                    ("Other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="AppliedUniversity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=55,
                    ),
                ),
                ("application_number", models.CharField(max_length=20)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
                "unique_together": {("student", "course")},
            },
        ),
    ]
