# Generated by Django 5.2.1 on 2025-11-13 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0024_document_sub_type_alter_document_doc_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applieduniversity",
            name="application_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name="StudentProfilePicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_uuid",
                    models.UUIDField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "google_file_id",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
            ],
        ),
    ]
