# Generated by Django 5.2.1 on 2025-11-13 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0025_alter_applieduniversity_application_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofilepicture",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_picture",
                to="student.student",
            ),
        ),
    ]
