# Generated by Django 5.2.1 on 2025-11-13 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0026_alter_studentprofilepicture_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Document Template",
                "verbose_name_plural": "Document Templates",
            },
        ),
        migrations.AlterField(
            model_name="document",
            name="file_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("student", "name")},
        ),
        migrations.CreateModel(
            name="TemplateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("Passport", "Passport"),
                            ("Transcript", "Transcript"),
                            ("Degree Certificate", "Degree Certificate"),
                            ("Recommendation Letter", "Recommendation Letter"),
                            ("Statement of Purpose", "Statement of Purpose"),
                            ("Resume", "Resume"),
                            ("Test Score Report", "Test Score Report"),
                            ("ID Proof", "ID Proof"),
                            ("Marksheet", "Marksheet"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("sub_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="student.documenttemplate",
                    ),
                ),
            ],
        ),
    ]
