# Generated by Django 5.2.1 on 2025-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0027_documenttemplate_alter_document_file_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="full_name",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="is_otp_verified",
            field=models.BooleanField(),
        ),
    ]
