# Generated by Django 5.2.1 on 2025-11-13 18:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0028_alter_student_full_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="templatedocument",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="templatedocument",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("in_review", "In Review"),
                    ("processing", "Processing"),
                ],
                db_index=True,
                default="uploaded",
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="templatedocument",
            unique_together={("template", "doc_type")},
        ),
        migrations.CreateModel(
            name="StudentDocumentRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_documents",
                        to="student.student",
                    ),
                ),
                (
                    "template_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_requirements",
                        to="student.templatedocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Document Requirement",
                "verbose_name_plural": "Student Document Requirements",
                "unique_together": {("student", "template_document")},
            },
        ),
    ]
