# Generated by Django 5.2.1 on 2025-11-13 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0029_alter_templatedocument_options_document_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="templatedocument",
            options={
                "verbose_name": "Template Document",
                "verbose_name_plural": "Template Documents",
            },
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="templatedocument",
            name="order",
        ),
        migrations.AddField(
            model_name="document",
            name="template_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_documents",
                to="student.templatedocument",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["student", "doc_type"], name="student_doc_student_71a959_idx"
            ),
        ),
    ]
