# Generated by Django 5.2.1 on 2025-11-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0030_alter_document_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="templatedocument",
            unique_together=set(),
        ),
    ]
