# Generated by Django 5.2.1 on 2025-11-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0031_alter_templatedocument_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("student", "template_document")},
        ),
    ]
