# Generated by Django 5.2.1 on 2025-11-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0033_alter_document_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("student", "template_document")},
        ),
    ]
