# Generated by Django 5.2.1 on 2025-11-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_course_tution_fees"),
        ("student", "0034_alter_document_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="document",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="document",
            name="student",
        ),
        migrations.RemoveField(
            model_name="document",
            name="template_document",
        ),
        migrations.RemoveField(
            model_name="templatedocument",
            name="template",
        ),
        migrations.AlterUniqueTogether(
            name="studentdocumentrequirement",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="studentdocumentrequirement",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentdocumentrequirement",
            name="template_document",
        ),
        migrations.AlterModelOptions(
            name="applieduniversity",
            options={
                "ordering": ["-applied_at"],
                "verbose_name": "Applied University",
                "verbose_name_plural": "Applied Universities",
            },
        ),
        migrations.AddIndex(
            model_name="applieduniversity",
            index=models.Index(
                fields=["student"], name="student_app_student_44eaaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="applieduniversity",
            index=models.Index(
                fields=["course"], name="student_app_course__deeb45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="applieduniversity",
            index=models.Index(
                fields=["application_number"], name="student_app_applica_e9d176_idx"
            ),
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.DeleteModel(
            name="DocumentTemplate",
        ),
        migrations.DeleteModel(
            name="StudentDocumentRequirement",
        ),
        migrations.DeleteModel(
            name="TemplateDocument",
        ),
    ]
