# Generated by Django 5.2.1 on 2025-11-16 21:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("student", "0035_alter_document_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("Passport", "Passport"),
                            ("Transcript", "Transcript"),
                            ("Degree Certificate", "Degree Certificate"),
                            ("Recommendation Letter", "Recommendation Letter"),
                            ("Statement of Purpose", "Statement of Purpose"),
                            ("Resume", "Resume"),
                            ("Test Score Report", "Test Score Report"),
                            ("ID Proof", "ID Proof"),
                            ("Marksheet", "Marksheet"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("sub_type", models.CharField(blank=True, max_length=100, null=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Document Type",
                "verbose_name_plural": "Document Types",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["doc_type"], name="student_doc_doc_typ_abb3f8_idx"
                    ),
                    models.Index(
                        fields=["is_default"], name="student_doc_is_defa_630d6a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentDocumentRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instructions", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.documenttype",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means this is a default required document.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_documents",
                        to="authentication.employee",
                    ),
                ),
                (
                    "requested_for_university",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only set if this document is required for a specific university.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="required_documents",
                        to="student.applieduniversity",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Document Requirement",
                "verbose_name_plural": "Student Document Requirements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_name",
                    models.CharField(blank=True, default=True, max_length=255),
                ),
                (
                    "counsellor_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("in_review", "In Review"),
                            ("processing", "Processing"),
                            ("re-do", "Upload Again"),
                        ],
                        default="uploaded",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "counsellor_comments",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("file_id", models.CharField(max_length=255)),
                (
                    "file_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "required_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file",
                        to="student.studentdocumentrequirement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="studentdocumentrequirement",
            index=models.Index(
                fields=["student"], name="student_stu_student_fc83aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentdocumentrequirement",
            index=models.Index(
                fields=["document_type"], name="student_stu_documen_d01886_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentdocumentrequirement",
            index=models.Index(
                fields=["requested_for_university"],
                name="student_stu_request_09b0e5_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentdocumentrequirement",
            unique_together={("student", "document_type", "requested_for_university")},
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["required_document"], name="student_doc_require_487c2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["counsellor_status"], name="student_doc_counsel_be9369_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["file_uuid"], name="student_doc_file_uu_966bec_idx"
            ),
        ),
    ]
