# Generated by Django 5.2.1 on 2025-11-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0036_documenttype_studentdocumentrequirement_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
