# Generated by Django 5.2.1 on 2025-11-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0037_alter_document_document_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="document_name",
            new_name="submitted_document",
        ),
    ]
