# Generated by Django 5.2.1 on 2026-01-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_milestone_studentmilestone_submilestonetemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetails',
            name='degree',
            field=models.CharField(choices=[('High School', 'High School'), ('Diploma', 'Diploma'), ('Associate', 'Associate'), ("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ('M.Phil', 'M.Phil'), ('Ph.D.', 'Ph.D.'), ('Post-Doctorate', 'Post-Doctorate'), ('Certificate', 'Certificate'), ('Other', 'Other')], max_length=50),
        ),
    ]
