# Generated by Django 5.2.1 on 2026-02-01 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0040_alter_educationdetails_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applieduniversity',
            name='application_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_details', to='student.student'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_details', to='student.student'),
        ),
    ]
