# Generated by Django 5.2.1 on 2026-02-05 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0041_alter_applieduniversity_application_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='call_timing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='counsellor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='follow_up_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='outcome',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='schedule_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('attempted', 'Attempted'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], db_index=True, default='requested', max_length=20),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='applieduniversity',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_universities', to='student.student'),
        ),
    ]
