# Generated by Django 5.2.1 on 2026-02-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_callrequest_call_timing_callrequest_counsellor_notes_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='callrequest',
            name='unique_student_employee_request',
        ),
        migrations.AlterField(
            model_name='applieduniversity',
            name='application_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
