# Generated by Django 5.2.1 on 2025-06-11 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ranking_agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('logo', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_url', models.URLField(max_length=1000)),
                ('cover_origin', models.URLField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE'), ('SEMI GOVERNMENT', 'SEMI GOVERNMENT'), ('GOVERNMENT', 'GOVERNMENT'), ('FUNDED', 'FUNDED')], max_length=50)),
                ('establish_year', models.DateField()),
                ('about', models.TextField()),
                ('admission_requirements', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='university', to='university.location')),
            ],
        ),
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=1000)),
                ('icon', models.TextField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='university.university')),
            ],
        ),
        migrations.CreateModel(
            name='faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='university.university')),
            ],
        ),
        migrations.CreateModel(
            name='university_ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=50)),
                ('ranking_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_rankings', to='university.ranking_agency')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='university.university')),
            ],
        ),
        migrations.CreateModel(
            name='videos_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='university.university')),
            ],
        ),
    ]
