# Generated by Django 5.2.1 on 2025-06-25 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, help_text='Name of the city', max_length=1000)),
                ('state', models.CharField(db_index=True, help_text='Name of the state or country', max_length=1000)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Partner_Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the partner agency', max_length=200)),
            ],
            options={
                'verbose_name': 'Partner Agency',
                'verbose_name_plural': 'Partner Agencies',
            },
        ),
        migrations.CreateModel(
            name='ranking_agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the ranking agency (e.g., QS, NIRF)', max_length=1000, unique=True)),
                ('description', models.TextField(help_text='Description of the agency and its methodology')),
                ('logo', models.URLField(db_index=True, help_text='Logo URL of the ranking agency', max_length=2000, unique=True)),
            ],
            options={
                'verbose_name': 'Ranking Agency',
                'verbose_name_plural': 'Ranking Agencies',
            },
        ),
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_url', models.URLField(help_text='Primary cover image URL for the university', max_length=1000, unique=True)),
                ('cover_origin', models.URLField(help_text='Original source of the cover image', max_length=1000)),
                ('name', models.CharField(db_index=True, help_text='Full name of the university', max_length=1000, unique=True)),
                ('type', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], db_index=True, help_text='Type of university: Public or Private', max_length=50)),
                ('establish_year', models.PositiveIntegerField(db_index=True, help_text='Year the university was established')),
                ('about', models.TextField(help_text='Brief description or history of the university')),
                ('admission_requirements', models.TextField(help_text='Eligibility and admission criteria')),
                ('location_map_link', models.URLField(db_index=True, help_text='Google Maps URL or any map link for the location', max_length=1000, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISH', 'PUBLISH')], db_index=True, default='DRAFT', help_text='Publishing status of the university data', max_length=50)),
                ('location', models.ForeignKey(help_text='Location where the university is situated', on_delete=django.db.models.deletion.PROTECT, related_name='universities', to='university.location')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Uni_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Name of the university's contact person", max_length=200)),
                ('designation', models.CharField(max_length=2000)),
                ('email', models.EmailField(db_index=True, help_text='Official email address', max_length=1000)),
                ('phone', models.CharField(db_index=True, help_text='Contact number (include country code)', max_length=20)),
                ('university', models.ForeignKey(help_text='Associated university', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='university.university')),
            ],
            options={
                'verbose_name': 'University Contact',
                'verbose_name_plural': 'University Contacts',
            },
        ),
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Statistic name (e.g., No. of Students)', max_length=100)),
                ('value', models.CharField(help_text='Value of the statistic (e.g., 20,000)', max_length=1000)),
                ('university', models.ForeignKey(help_text='University this statistic is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='university.university')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
            },
        ),
        migrations.CreateModel(
            name='mou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MoU_copy_link', models.URLField(max_length=2000)),
                ('SigningDate', models.DateField()),
                ('ExpiryDate', models.DateField()),
                ('Duration_in_years', models.PositiveIntegerField(help_text='Duration in Years')),
                ('Duration_in_Months', models.PositiveIntegerField(help_text='Duration in Years')),
                ('university', models.ForeignKey(help_text='University this commission is assigned to', on_delete=django.db.models.deletion.CASCADE, to='university.university')),
            ],
            options={
                'verbose_name': 'MoU',
                'verbose_name_plural': 'MoU',
            },
        ),
        migrations.CreateModel(
            name='faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(db_index=True, help_text='Frequently asked question', unique=True)),
                ('answer', models.TextField(help_text='Answer to the question', unique=True)),
                ('university', models.ForeignKey(help_text='University this FAQ belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='university.university')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inPercentage', models.PositiveIntegerField(blank=True, help_text='Commission value in Percentage', null=True)),
                ('inAmount', models.PositiveIntegerField(blank=True, help_text='Commission value in Rupees', null=True)),
                ('partner_agency', models.ForeignKey(help_text='Partner agency for this commission', on_delete=django.db.models.deletion.PROTECT, to='university.partner_agency')),
                ('university', models.ForeignKey(help_text='University this commission is assigned to', on_delete=django.db.models.deletion.CASCADE, to='university.university')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
            },
        ),
        migrations.CreateModel(
            name='videos_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, help_text='Video link (e.g., YouTube) related to the university', max_length=2000)),
                ('university', models.ForeignKey(help_text='University this video is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='university.university')),
            ],
            options={
                'verbose_name': 'Video Link',
                'verbose_name_plural': 'Video Links',
            },
        ),
        migrations.CreateModel(
            name='university_ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(db_index=True, help_text='Rank assigned to the university', max_length=50)),
                ('ranking_agency', models.ForeignKey(help_text='Agency that provided the ranking', on_delete=django.db.models.deletion.CASCADE, related_name='university_rankings', to='university.ranking_agency')),
                ('university', models.ForeignKey(help_text='University being ranked', on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='university.university')),
            ],
            options={
                'verbose_name': 'University Ranking',
                'verbose_name_plural': 'University Rankings',
                'unique_together': {('university', 'ranking_agency')},
            },
        ),
    ]
