# Generated by Django 5.2.1 on 2025-07-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner_agency',
            name='partner_type',
            field=models.CharField(choices=[('Preferred Partner', 'Preferred Partner'), ('Standard Partner', 'Standard Partner')], default='Preferred Partner', max_length=80),
        ),
    ]
