# Generated by Django 5.2.1 on 2025-06-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='ranking_agency',
            options={'verbose_name': 'Ranking Agency', 'verbose_name_plural': 'Ranking Agencies'},
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name': 'Statistic', 'verbose_name_plural': 'Statistics'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterModelOptions(
            name='university_ranking',
            options={'verbose_name': 'University Ranking', 'verbose_name_plural': 'University Rankings'},
        ),
        migrations.AlterModelOptions(
            name='videos_links',
            options={'verbose_name': 'Video Link', 'verbose_name_plural': 'Video Links'},
        ),
    ]
