# Generated by Django 5.2.1 on 2025-06-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_faqs_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_map_link',
            field=models.URLField(default='https://excalidraw.com/', max_length=1000),
            preserve_default=False,
        ),
    ]
