# Generated by Django 5.2.1 on 2025-07-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_partner_agency_partner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(db_index=True, default='', help_text='Name of the country', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(db_index=True, help_text='Name of the state', max_length=1000),
        ),
    ]
