# Generated by Django 5.2.1 on 2025-06-19 19:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_location_location_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='commission',
            field=models.PositiveIntegerField(default=0, help_text='Commission should always be in rupees', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='university',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISH', 'PUBLISH')], db_index=True, default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='answer',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='question',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_map_link',
            field=models.URLField(db_index=True, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_index=True, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='ranking_agency',
            name='logo',
            field=models.URLField(db_index=True, max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='ranking_agency',
            name='name',
            field=models.CharField(db_index=True, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stats',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='university.university'),
        ),
        migrations.AlterField(
            model_name='university',
            name='cover_url',
            field=models.URLField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='establish_year',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='universities', to='university.location'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(db_index=True, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='type',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE'), ('SEMI GOVERNMENT', 'SEMI GOVERNMENT'), ('GOVERNMENT', 'GOVERNMENT'), ('FUNDED', 'FUNDED')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='university_ranking',
            name='rank',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='videos_links',
            name='url',
            field=models.URLField(db_index=True, max_length=2000),
        ),
        migrations.AlterUniqueTogether(
            name='university_ranking',
            unique_together={('university', 'ranking_agency')},
        ),
        migrations.CreateModel(
            name='Uni_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=1000)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='university.university')),
            ],
            options={
                'verbose_name': 'University official',
                'verbose_name_plural': 'University Officials',
            },
        ),
    ]
