# Generated by Django 5.2.1 on 2025-07-21 16:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_location_country_alter_location_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the country', max_length=1000, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AddField(
            model_name='university',
            name='review_rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AdmissionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_type', models.CharField(choices=[('UNDERGRADUATE', 'UNDERGRADUATE'), ('GRADUATE', 'GRADUATE')], max_length=50)),
                ('GPA_min', models.PositiveIntegerField()),
                ('GPA_max', models.PositiveIntegerField()),
                ('SAT_min', models.PositiveIntegerField()),
                ('SAT_max', models.PositiveIntegerField()),
                ('ACT_min', models.PositiveIntegerField()),
                ('ACT_max', models.PositiveIntegerField()),
                ('IELTS_min', models.PositiveIntegerField()),
                ('IELTS_max', models.PositiveIntegerField()),
                ('university', models.ForeignKey(help_text='University this Admission stats is assigned to', on_delete=django.db.models.deletion.CASCADE, to='university.university')),
            ],
        ),
        migrations.CreateModel(
            name='CostOfLiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_min', models.DecimalField(decimal_places=2, help_text='Minimum rent cost in Australian Dollars (AUD)', max_digits=10)),
                ('rent_max', models.DecimalField(decimal_places=2, help_text='Maximum rent cost in Australian Dollars (AUD)', max_digits=10)),
                ('food_min', models.DecimalField(decimal_places=2, help_text='Minimum food cost in Australian Dollars (AUD)', max_digits=10)),
                ('food_max', models.DecimalField(decimal_places=2, help_text='Maximum food cost in Australian Dollars (AUD)', max_digits=10)),
                ('transport_min', models.DecimalField(decimal_places=2, help_text='Minimum transport cost in Australian Dollars (AUD)', max_digits=10)),
                ('transport_max', models.DecimalField(decimal_places=2, help_text='Maximum transport cost in Australian Dollars (AUD)', max_digits=10)),
                ('miscellaneous_min', models.DecimalField(decimal_places=2, help_text='Minimum miscellaneous cost in Australian Dollars (AUD)', max_digits=10)),
                ('miscellaneous_max', models.DecimalField(decimal_places=2, help_text='Maximum miscellaneous cost in Australian Dollars (AUD)', max_digits=10)),
                ('total_min', models.DecimalField(decimal_places=2, help_text='Minimum total cost of living in Australian Dollars (AUD)', max_digits=10)),
                ('total_max', models.DecimalField(decimal_places=2, help_text='Maximum total cost of living in Australian Dollars (AUD)', max_digits=10)),
                ('country', models.ForeignKey(help_text='The country this cost of living data is related to', on_delete=django.db.models.deletion.CASCADE, related_name='cost_of_living', to='university.country')),
            ],
            options={
                'verbose_name': 'Cost of Living',
                'verbose_name_plural': 'Costs of Living',
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('cost', models.PositiveIntegerField()),
                ('type_of_visa', models.CharField(choices=[('TOURIST', 'Tourist Visa'), ('BUSINESS', 'Business Visa'), ('WORK', 'Work Visa'), ('STUDENT', 'Student Visa'), ('TRANSIT', 'Transit Visa'), ('IMMIGRANT', 'Immigrant Visa'), ('FAMILY', 'Family Reunion Visa'), ('DIPLOMATIC', 'Diplomatic/Official Visa'), ('MEDICAL', 'Medical Visa'), ('REFUGEE', 'Refugee/Asylum Visa'), ('SPECIAL', 'Special Purpose Visa'), ('E_VISA', 'e-Visa/Visa on Arrival')], help_text='Type of visa', max_length=20)),
                ('describe', models.TextField(max_length=10000)),
                ('university', models.ForeignKey(help_text='University this Visa is assigned to', on_delete=django.db.models.deletion.CASCADE, to='university.university')),
            ],
            options={
                'verbose_name': 'Visa',
                'verbose_name_plural': 'Visas',
            },
        ),
        migrations.CreateModel(
            name='WhyStudyInSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Detailed content about why to study in this country, comma seperated')),
                ('country', models.ForeignKey(help_text='The country this section is related to', on_delete=django.db.models.deletion.CASCADE, related_name='study_sections', to='university.country')),
            ],
            options={
                'verbose_name': 'WhyStudyIn',
                'verbose_name_plural': 'WhyStudyIn Sections',
            },
        ),
        migrations.CreateModel(
            name='WorkOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('university', models.ForeignKey(help_text='University this Visa is assigned to', on_delete=django.db.models.deletion.CASCADE, to='university.university')),
            ],
        ),
    ]
