# Generated by Django 5.2.1 on 2025-07-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_country_university_review_rating_admissionstats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionstats',
            options={'verbose_name': 'Admission Stats', 'verbose_name_plural': 'Admission Stats'},
        ),
        migrations.AddField(
            model_name='university',
            name='avg_acceptance_rate',
            field=models.PositiveIntegerField(default=0, help_text='in percentage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='avg_tution_fee',
            field=models.PositiveIntegerField(default=0, help_text='in USD'),
            preserve_default=False,
        ),
    ]
