# Generated by Django 5.2.1 on 2025-07-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_country_university_review_rating_admissionstats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionstats',
            options={'verbose_name': 'Admission Stats', 'verbose_name_plural': 'Admission Stats'},
        ),
    ]
