# Generated by Django 5.2.1 on 2025-06-19 20:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_university_commission_university_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='answer',
            field=models.TextField(help_text='Answer to the above question', unique=True),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='question',
            field=models.TextField(db_index=True, help_text='Frequently asked question', unique=True),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='university',
            field=models.ForeignKey(help_text='University this FAQ belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='university.university'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_map_link',
            field=models.URLField(db_index=True, help_text='Google Maps URL or any map link for the location', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the location or city', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='ranking_agency',
            name='description',
            field=models.TextField(help_text='Brief description of the agency and its methodology'),
        ),
        migrations.AlterField(
            model_name='ranking_agency',
            name='logo',
            field=models.URLField(db_index=True, help_text='Agency logo URL', max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='ranking_agency',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the ranking agency (e.g., QS, NIRF)', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='icon',
            field=models.TextField(help_text='Icon (SVG or class name) representing this stat'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='name',
            field=models.CharField(db_index=True, help_text='Stat name (e.g., No. of Students, Courses)', max_length=100),
        ),
        migrations.AlterField(
            model_name='stats',
            name='university',
            field=models.ForeignKey(help_text='University this statistic is related to', on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='university.university'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='value',
            field=models.CharField(help_text='Value of the statistic (e.g., 20,000 students)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='uni_contact',
            name='email',
            field=models.EmailField(db_index=True, help_text='Official email ID', max_length=1000),
        ),
        migrations.AlterField(
            model_name='uni_contact',
            name='name',
            field=models.CharField(db_index=True, help_text="Name of the university's official or contact person", max_length=200),
        ),
        migrations.AlterField(
            model_name='uni_contact',
            name='phone',
            field=models.CharField(db_index=True, help_text='Contact number (include country code if necessary)', max_length=20),
        ),
        migrations.AlterField(
            model_name='uni_contact',
            name='university',
            field=models.ForeignKey(help_text='Associated university', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='university.university'),
        ),
        migrations.AlterField(
            model_name='university',
            name='about',
            field=models.TextField(help_text='Brief description or history of the university'),
        ),
        migrations.AlterField(
            model_name='university',
            name='admission_requirements',
            field=models.TextField(help_text='Eligibility and admission criteria'),
        ),
        migrations.AlterField(
            model_name='university',
            name='commission',
            field=models.PositiveIntegerField(default=0, help_text='Commission amount (in INR) applicable per admission', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='university',
            name='cover_origin',
            field=models.URLField(help_text='Original source of the cover image', max_length=1000),
        ),
        migrations.AlterField(
            model_name='university',
            name='cover_url',
            field=models.URLField(help_text='Primary cover image URL for the university', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='establish_year',
            field=models.DateField(db_index=True, help_text='Year the university was established'),
        ),
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.ForeignKey(help_text='Location where the university is situated', on_delete=django.db.models.deletion.PROTECT, related_name='universities', to='university.location'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(db_index=True, help_text='Full name of the university', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISH', 'PUBLISH')], db_index=True, default='DRAFT', help_text='Publishing status of the university data', max_length=50),
        ),
        migrations.AlterField(
            model_name='university',
            name='type',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE'), ('SEMI GOVERNMENT', 'SEMI GOVERNMENT'), ('GOVERNMENT', 'GOVERNMENT'), ('FUNDED', 'FUNDED')], db_index=True, help_text='Type of university: Public, Private, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='university_ranking',
            name='rank',
            field=models.CharField(db_index=True, help_text='Rank assigned to the university', max_length=50),
        ),
        migrations.AlterField(
            model_name='university_ranking',
            name='ranking_agency',
            field=models.ForeignKey(help_text='Agency that provided the ranking', on_delete=django.db.models.deletion.CASCADE, related_name='university_rankings', to='university.ranking_agency'),
        ),
        migrations.AlterField(
            model_name='university_ranking',
            name='university',
            field=models.ForeignKey(help_text='University being ranked', on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='university.university'),
        ),
        migrations.AlterField(
            model_name='videos_links',
            name='university',
            field=models.ForeignKey(help_text='University this video is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='university.university'),
        ),
        migrations.AlterField(
            model_name='videos_links',
            name='url',
            field=models.URLField(db_index=True, help_text='YouTube or any video link relevant to the university', max_length=2000),
        ),
    ]
