# Generated by Django 5.2.1 on 2025-06-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_alter_faqs_answer_alter_faqs_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_map_link',
        ),
        migrations.AddField(
            model_name='university',
            name='location_map_link',
            field=models.URLField(db_index=True, default='', help_text='Google Maps URL or any map link for the location', max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
