# Generated by Django 5.2.1 on 2025-07-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_alter_admissionstats_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='answer',
            field=models.TextField(help_text='Answer to the question'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='question',
            field=models.TextField(db_index=True, help_text='Frequently asked question'),
        ),
    ]
