# Generated by Django 5.2.1 on 2025-07-22 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_alter_faqs_answer_alter_faqs_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstats',
            name='ACT_max',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='admissionstats',
            name='ACT_min',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='admissionstats',
            name='GPA_max',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='admissionstats',
            name='GPA_min',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='admissionstats',
            name='IELTS_max',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='admissionstats',
            name='IELTS_min',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='admissionstats',
            name='SAT_max',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='admissionstats',
            name='SAT_min',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
