# Generated by Django 5.2.1 on 2025-07-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_alter_admissionstats_options'),
        ('university', '0006_alter_faqs_answer_alter_faqs_question'),
    ]

    operations = [
    ]
