# Generated by Django 5.2.1 on 2025-06-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_remove_location_location_map_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(db_index=True, default='', help_text='Name of the city', max_length=1000, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(db_index=True, default='', help_text='Name of the state or country', max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
