# Generated by Django 5.2.1 on 2025-06-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_remove_location_name_location_city_location_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(db_index=True, help_text='Name of the city', max_length=1000),
        ),
    ]
