# Generated by Django 5.2.1 on 2025-07-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_alter_admissionstats_act_max_and_more'),
        ('university', '0007_merge_20250722_0148'),
    ]

    operations = [
    ]
