# Generated by Django 5.2.1 on 2025-06-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_alter_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(db_index=True, help_text='Name of the state or country', max_length=1000),
        ),
    ]
