# Generated by Django 5.2.1 on 2025-06-23 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_alter_location_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner_Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the partner agency', max_length=200)),
            ],
            options={
                'verbose_name': 'Partner Agency',
                'verbose_name_plural': 'Partner Agencies',
            },
        ),
        migrations.AlterModelOptions(
            name='uni_contact',
            options={'verbose_name': 'University Contact', 'verbose_name_plural': 'University Contacts'},
        ),
        migrations.RemoveField(
            model_name='university',
            name='commission',
        ),
        migrations.AlterField(
            model_name='faqs',
            name='answer',
            field=models.TextField(help_text='Answer to the question', unique=True),
        ),
        migrations.AlterField(
            model_name='ranking_agency',
            name='description',
            field=models.TextField(help_text='Description of the agency and its methodology'),
        ),
        migrations.AlterField(
            model_name='ranking_agency',
            name='logo',
            field=models.URLField(db_index=True, help_text='Logo URL of the ranking agency', max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='icon',
            field=models.TextField(help_text='Icon (SVG or class name) for this stat'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='name',
            field=models.CharField(db_index=True, help_text='Statistic name (e.g., No. of Students)', max_length=100),
        ),
        migrations.AlterField(
            model_name='stats',
            name='university',
            field=models.ForeignKey(help_text='University this statistic is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='university.university'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='value',
            field=models.CharField(help_text='Value of the statistic (e.g., 20,000)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='uni_contact',
            name='email',
            field=models.EmailField(db_index=True, help_text='Official email address', max_length=1000),
        ),
        migrations.AlterField(
            model_name='uni_contact',
            name='name',
            field=models.CharField(db_index=True, help_text="Name of the university's contact person", max_length=200),
        ),
        migrations.AlterField(
            model_name='uni_contact',
            name='phone',
            field=models.CharField(db_index=True, help_text='Contact number (include country code)', max_length=20),
        ),
        migrations.AlterField(
            model_name='university',
            name='type',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], db_index=True, help_text='Type of university: Public or Private', max_length=50),
        ),
        migrations.AlterField(
            model_name='videos_links',
            name='university',
            field=models.ForeignKey(help_text='University this video is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='university.university'),
        ),
        migrations.AlterField(
            model_name='videos_links',
            name='url',
            field=models.URLField(db_index=True, help_text='Video link (e.g., YouTube) related to the university', max_length=2000),
        ),
        migrations.CreateModel(
            name='commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.PositiveIntegerField(help_text='Commission value (e.g., percentage)')),
                ('university', models.ForeignKey(help_text='University this commission is assigned to', on_delete=django.db.models.deletion.CASCADE, to='university.university')),
                ('partner_agency', models.ForeignKey(help_text='Partner agency for this commission', on_delete=django.db.models.deletion.PROTECT, to='university.partner_agency')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
            },
        ),
    ]
