# Generated by Django 5.2.1 on 2025-07-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_alter_admissionstats_act_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costofliving',
            name='food_max',
            field=models.DecimalField(decimal_places=2, help_text='Maximum food cost in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='costofliving',
            name='food_min',
            field=models.DecimalField(decimal_places=2, help_text='Minimum food cost in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='costofliving',
            name='miscellaneous_max',
            field=models.DecimalField(decimal_places=2, help_text='Maximum miscellaneous cost in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='costofliving',
            name='miscellaneous_min',
            field=models.DecimalField(decimal_places=2, help_text='Minimum miscellaneous cost in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='costofliving',
            name='rent_max',
            field=models.DecimalField(decimal_places=2, help_text='Maximum rent cost in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='costofliving',
            name='rent_min',
            field=models.DecimalField(decimal_places=2, help_text='Minimum rent cost in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='costofliving',
            name='total_max',
            field=models.DecimalField(decimal_places=2, help_text='Maximum total cost of living in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='costofliving',
            name='total_min',
            field=models.DecimalField(decimal_places=2, help_text='Minimum total cost of living in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='costofliving',
            name='transport_max',
            field=models.DecimalField(decimal_places=2, help_text='Maximum transport cost in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='costofliving',
            name='transport_min',
            field=models.DecimalField(decimal_places=2, help_text='Minimum transport cost in USD', max_digits=10),
        ),
    ]
