# Generated by Django 5.2.1 on 2025-06-23 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_partner_agency_alter_uni_contact_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='commission',
        ),
        migrations.AddField(
            model_name='commission',
            name='inAmount',
            field=models.PositiveIntegerField(blank=True, help_text='Commission value in Rupees', null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='inPercentage',
            field=models.PositiveIntegerField(blank=True, help_text='Commission value in Percentage', null=True),
        ),
        migrations.AddField(
            model_name='uni_contact',
            name='designation',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university',
            name='establish_year',
            field=models.PositiveIntegerField(db_index=True, help_text='Year the university was established'),
        ),
        migrations.CreateModel(
            name='mou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MoU_copy_link', models.URLField(max_length=2000)),
                ('SigningDate', models.DateField()),
                ('ExpiryDate', models.DateField()),
                ('Duration_of_MoU', models.PositiveIntegerField(help_text='Duration in Years')),
                ('university', models.ForeignKey(help_text='University this commission is assigned to', on_delete=django.db.models.deletion.CASCADE, to='university.university')),
            ],
            options={
                'verbose_name': 'MoU',
                'verbose_name_plural': 'MoU',
            },
        ),
    ]
