# Generated by Django 5.2.1 on 2025-07-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_alter_costofliving_food_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workopportunity',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
