# Generated by Django 5.2.1 on 2025-06-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_remove_commission_commission_commission_inamount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='icon',
        ),
    ]
