# Generated by Django 5.2.1 on 2025-07-30 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_alter_workopportunity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstats',
            name='application_fee',
            field=models.PositiveIntegerField(default=0, help_text='Appliaction fee for this university'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CountryFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='university.country')),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='university.country')),
            ],
        ),
        migrations.CreateModel(
            name='CountryRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_rankings', to='university.country')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.university')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('country', 'rank')},
            },
        ),
    ]
