# Generated by Django 5.2.1 on 2025-06-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_remove_stats_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mou',
            name='Duration_of_MoU',
        ),
        migrations.AddField(
            model_name='mou',
            name='Duration_in_Months',
            field=models.PositiveIntegerField(default=0, help_text='Duration in Years'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mou',
            name='Duration_in_years',
            field=models.PositiveIntegerField(default=0, help_text='Duration in Years'),
            preserve_default=False,
        ),
    ]
