# Generated by Django 5.2.1 on 2025-07-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_admissionstats_application_fee_countryfaq_fact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountryRanking',
            new_name='CountryWiseRanking',
        ),
    ]
