# Generated by Django 5.2.1 on 2025-07-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_rename_countryranking_countrywiseranking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countrywiseranking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='countrywiseranking',
            name='country',
        ),
        migrations.RemoveField(
            model_name='countrywiseranking',
            name='university',
        ),
        migrations.AlterField(
            model_name='admissionstats',
            name='application_fee',
            field=models.PositiveIntegerField(help_text='Application fee for this university'),
        ),
        migrations.DeleteModel(
            name='CountryFAQ',
        ),
        migrations.DeleteModel(
            name='CountryWiseRanking',
        ),
    ]
