# Generated by Django 5.2.1 on 2025-09-14 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0015_alter_countrywiseranking_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faqs', to='university.country')),
            ],
        ),
    ]
