# Generated by Django 5.2.1 on 2025-11-26 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0016_countryfaq"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryVisa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("cost", models.PositiveIntegerField()),
                (
                    "type_of_visa",
                    models.CharField(
                        choices=[
                            ("TOURIST", "Tourist Visa"),
                            ("BUSINESS", "Business Visa"),
                            ("WORK", "Work Visa"),
                            ("STUDENT", "Student Visa"),
                            ("TRANSIT", "Transit Visa"),
                            ("IMMIGRANT", "Immigrant Visa"),
                            ("FAMILY", "Family Reunion Visa"),
                            ("DIPLOMATIC", "Diplomatic/Official Visa"),
                            ("MEDICAL", "Medical Visa"),
                            ("REFUGEE", "Refugee/Asylum Visa"),
                            ("SPECIAL", "Special Purpose Visa"),
                            ("E_VISA", "e-Visa/Visa on Arrival"),
                        ],
                        help_text="Type of visa",
                        max_length=20,
                    ),
                ),
                ("describe", models.TextField(max_length=10000)),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Country this visa belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visas",
                        to="university.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visa",
                "verbose_name_plural": "Visas",
            },
        ),
    ]
