# Generated by Django 5.2.1 on 2025-11-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0018_alter_countryvisa_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="university",
            name="cover_origin",
        ),
        migrations.DeleteModel(
            name="Visa",
        ),
    ]
