# Generated by Django 5.2.1 on 2026-02-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0019_remove_university_cover_origin_delete_visa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstats',
            name='admission_type',
            field=models.CharField(choices=[('UNDERGRADUATE', 'UNDERGRADUATE'), ('GRADUATE', 'GRADUATE'), ('PHD', 'Doctorate(PhD)')], max_length=50),
        ),
    ]
