# Generated by Django 5.2.1 on 2025-09-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='marks_obtained',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, null=True, to='exams.option'),
        ),
    ]
