# Generated by Django 5.2.1 on 2025-09-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='negative_marking_factor',
            field=models.FloatField(choices=[(0, 'None'), (0.25, '1/4'), (0.5, '1/2'), (0.33, '1/3'), (0.2, '1/5')], default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
    ]
