# Generated by Django 5.2.1 on 2025-09-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_test_options_test_updated_at_testrules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststatus',
            name='valid_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
