# Generated by Django 5.2.1 on 2025-09-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_test_negative_marking_factor_test_total_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tests',
        ),
        migrations.RemoveField(
            model_name='coursetest',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursetest',
            name='test',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='evaluated_by',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='test_status',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='created_by_employee',
        ),
        migrations.RemoveField(
            model_name='teststatus',
            name='test',
        ),
        migrations.RemoveField(
            model_name='teststatus',
            name='student',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseTest',
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestStatus',
        ),
    ]
