# Generated by Django 5.2.1 on 2025-09-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_answer_marks_obtained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='exams.option'),
        ),
    ]
