# Generated by Django 5.2.1 on 2025-10-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_answer_selected_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
