# Generated by Django 5.2.1 on 2025-09-29 19:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('student', '0017_assignedcounsellor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('creator_employee', models.ForeignKey(blank=True, help_text='Employee who created this task, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='authentication.employee')),
                ('creator_student', models.ForeignKey(blank=True, help_text='Student who created this task, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='student.student')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='authentication.employee')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='student.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Task Assignment',
                'verbose_name_plural': 'Task Assignments',
                'constraints': [models.UniqueConstraint(fields=('task', 'employee', 'student'), name='unique_task_assignment')],
            },
        ),
    ]
