# Generated by Django 5.2.1 on 2025-09-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_completed_task_priority_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignment',
            name='completed',
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('inprogress', 'In Progress'), ('completed', 'Completed')], default='todo', max_length=20),
        ),
    ]
