# Generated by Django 5.2.1 on 2026-01-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_taskassignment_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('inprogress', 'In Progress'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='todo', max_length=20),
        ),
    ]
