# Generated by Django 5.2.1 on 2025-09-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanitizedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(db_index=True, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sanitized Search',
                'verbose_name_plural': 'Sanitized Searches',
                'db_table': 'sanitized_searches',
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='UnsanitizedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(db_index=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Unsanitized Search',
                'verbose_name_plural': 'Unsanitized Searches',
                'db_table': 'unsanitized_searches',
                'ordering': ['-count'],
            },
        ),
    ]
